#!/bin/sh
#
# Specifically for windows, where installing autoconf looks suspiciously
# like boiling the ocean.

if [ "$RUNNER_OS" = "Windows" ]; then
    CFLAGS="$CFLAGS -I $(pwd)/. -I $(pwd)/win32"
fi

cat Makefile.in | sed \
    -e "s%@N2N_VERSION_SHORT@%FIXME%g" \
    -e "s%@GIT_COMMITS@%FIXME%g" \
    -e "s%@CC@%gcc%g" \
    -e "s%@AR@%ar%g" \
    -e "s%@CFLAGS@%$CFLAGS%g" \
    -e "s%@LDFLAGS@%$LDFLAGS%g" \
    -e "s%@N2N_LIBS@%%g" \
    > Makefile

cat tools/Makefile.in | sed \
    -e "s%@CC@%gcc%g" \
    -e "s%@N2N_LIBS@%%g" \
    -e "s%@CFLAGS@%$CFLAGS%g" \
    -e "s%@LDFLAGS@%$LDFLAGS%g" \
    -e "s%@ADDITIONAL_TOOLS@%%g" \
    > tools/Makefile

cat <<EOF >include/config.h
#define PACKAGE_VERSION "FIXME"
#define PACKAGE_OSNAME "FIXME"
#define GIT_RELEASE "FIXME"
EOF
