#!/bin/sh
#
# Specifically for windows, where installing autoconf looks suspiciously
# like boiling the ocean.

OS=$(uname -o)
if [ "$OS" = "Msys" ]; then
    CFLAGS="$CFLAGS -I. -I./win32"
    LDLIBS="$LDLIBS -lws2_32 -liphlpapi"
fi

cat Makefile.in | sed \
    -e "s%@N2N_VERSION_SHORT@%FIXME%g" \
    -e "s%@GIT_COMMITS@%FIXME%g" \
    -e "s%@CC@%gcc%g" \
    -e "s%@AR@%ar%g" \
    -e "s%@CFLAGS@%$CFLAGS%g" \
    -e "s%@LDFLAGS@%$LDFLAGS%g" \
    -e "s%@N2N_LIBS@%$LDLIBS%g" \
    > Makefile

cat tools/Makefile.in | sed \
    -e "s%@CC@%gcc%g" \
    -e "s%@ADDITIONAL_TOOLS@%%g" \
    > tools/Makefile

cat <<EOF >include/config.h
#define PACKAGE_VERSION "FIXME"
#define PACKAGE_OSNAME "FIXME"
#define GIT_RELEASE "FIXME"
EOF
