#!/bin/sh
#
# This expects to find the tests in the tools dir and the expected results
# in the tests dir

TESTS="
    tests-compress
    tests-elliptic
    tests-hashing
    tests-transform
    tests-wire
"

TOOLSDIR=tools
TESTDATA=tests

if [ ! -d "$TOOLSDIR" -o ! -d "$TESTDATA" ]; then
    echo Could not find either TOOLSDIR or TESTDATA, run from top dir
    exit 1
fi

set -e
for i in $TESTS; do
    echo "$TOOLSDIR/$i >$TESTDATA/$i.out"
    $TOOLSDIR/$i >$TESTDATA/$i.out
    cmp $TESTDATA/$i.expected $TESTDATA/$i.out
done
